### ISSUE TITLE
Request an update for compatibility with Jeedom v4.4.2 core

### ISSUE THREAD

**Issue by jngdan** [Spine34/jeedom-widgets#1]
Hi,
Do you think that it will be possible to update your code to make yours gauges widgets compatible with the last new version of Jeedom core v4.4.2 and + ? 
Currently, I experienced a blank widget with the new core. 
Thanks a lot !

**Comment by Spine34** [comment]
Good morning,

See here : https://community.jeedom.com/t/widget-solid-gauge/124148
